### ISSUE TITLE
[Data] Dotnet Core data generator for shipment/onhand data

### ISSUE THREAD

**Issue by codepossible** [cse-southeast-devcrew/openhack-durable-entities-coach#11]
### Description
*As Joe, I'd like to play with a wide variety of test data so that I can get an idea of what the data may look like within the system and also so that I can test my code against a dynamic set of data*

*As Ralph, I'd like to understand the data flowing through the system so that I can model my data analysis using an example data set*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] A data generation tool is built that enables the automated generation of shipment and onhand documents
- [ ] The tool should accept *???* as input and produce its output as *???* (cc @ianphil)
- [ ] The tool should reside within the *???* folder (cc @ianphil)

### Resources
**Technical Design Document**
N/A

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
