### ISSUE TITLE
[Pre-req] Dev Container

### ISSUE THREAD

**Issue by codepossible** [cse-southeast-devcrew/openhack-durable-entities-coach#18]
### Description
As Joe, I'd like to have a uniform development environment, so that I know I have all the needed components for building our services.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should contain Azure Function Core Tools, Azure CLI, Dotnet Core SDK
- [ ] Should run in docker using VSCode devContainer
- [ ] Should be located in starter folder

Also, here are a few points that need to be addressed:

1. n/a

### Resources
[https://code.visualstudio.com/docs/remote/containers](https://code.visualstudio.com/docs/remote/containers)

### Tasks
- [ ] Create Dockerfile with depndancies
- [ ] Create post configuration script
- [ ] Update readme in starter folder
