### ISSUE TITLE
[Design] All Document/Event Schemas

### ISSUE THREAD

**Issue by ianphil** [cse-southeast-devcrew/openhack-durable-entities-coach#28]
### Description
As Pratibha, I'd like to understand the data schema of the documents and events , in order to predict the contract between services.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should contain the input document schema for shipment information
- [ ] Should contain the input document schema for onhand information
- [ ] Should contain the Cosmos Changefeed for shipment event schema
- [ ] Should contain the Cosmos Changefeed for onhand event schema
- [ ] Should contain the event schema for shipment that is passed from client to orchestrator
- [ ] Should contain the event schema for onhand that is passed from client to orchestrator
- [ ] Should contain the event schema for shipment that is passed from orchestrator to entity
- [ ] Should contain the event schema for onhand that is passed from orchestrator to entity
- [ ] Should contain the Document schema the entity writes to the MDS collection

Also, here are a few points that need to be addressed:

1. Should be in a markdown design file checked into the docs folder in the repo
2. Does not need to contain how the data flows, simply the json representation of each data type

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] https://github.com/microsoft/code-with-engineering-playbook/blob/master/backlog-management/minimal-slices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
