### ISSUE TITLE
[Ch02] Orchestrator Function

### ISSUE THREAD

**Issue by ianphil** [cse-southeast-devcrew/openhack-durable-entities-coach#7]
### Description
As Joe, I'd like to create an orchestrator function , in order to control how entities are partitioned.

### Acceptance Criteria
- [x] Change feed data should be mapped into events (shipping, on hand)
- [x] Send a collection of events to the orchestrator
- [x] Should accept event data from upstream client function
- [x] Should partition entities by storeId
- [x] Should signal/call entity with event information using a proxy (see Resources link)
- [x] Should follow along with the work done in the validation spike [here](https://github.com/ianphil/spike-inventory-de/blob/5c744fdd7dfe2660559de985d56235ab0144af0b/InventoryCosmosTrigger/index.ts#L13)

### Resources
[https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities#example-orchestration-first-signals-then-calls-entity-through-proxy](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities#example-orchestration-first-signals-then-calls-entity-through-proxy)

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by ianphil** [comment]
partition by store, create entity proxy
